name: Feishu synchronize

on:
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  deployment_status:
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created]
  issues:
    types: [opened, edited, milestoned, pinned, reopened]
  issue_comment:
    types: [created]
  milestone:
    types: [opened, deleted]
  project_card:
    types: [created]
  pull_request:
    branches: ['main', 'master']
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: ['main', 'master']

jobs:
  send-event:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: junka/feishu-bot-webhook-action@main
        with:
          webhook: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          signkey: ${{ secrets.FEISHU_BOT_SIGNKEY }}
      - name: Debug Secrets
        run: |
          echo "FEISHU_BOT_WEBHOOK is set: $FEISHU_BOT_WEBHOOK"
          echo "FEISHU_BOT_SIGNKEY is set: $FEISHU_BOT_SIGNKEY"
        env:
          FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          FEISHU_BOT_SIGNKEY: ${{ secrets.FEISHU_BOT_SIGNKEY }}
